permalink: /:year/:month/:day.html
markdown: redcarpet

redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'space_after_headers']
safe: true
lsi: false
pygments: true
baseurl:/carl
url:http://codingnow.github.io.carl
main_menu:
- label:About
  url:about_me.html
